config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-cloud:
      branch: master
      repo: https://github.com/I2PC/scipion-cloud
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  SvcQC.Dep:
    repos:
      github.com/I2PC/scipion-cloud im_client:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-mauve-hare.sh
        container: svcqc.dep_crappy-cobalt-impala
timeout: 5400
